version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672
  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
  metric:
    build:
      context: ./metric
    restart: always
#    volumes:
#      - service-data-volume:/service_data
    volumes:
        - ./service_data:/service_data
    depends_on:
      - rabbitmq
      - features
      - model
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
  plot:
    build:
      context: ./plot
    restart: always
#    volumes:
#      - service-data-volume:/service_data
    volumes:
        - ./service_data:/service_data
    depends_on:
      - metric

#volumes:
#  service-data-volume:
#    name: "service-data-volume"
#networks:
#  bdn:
#    name: bdn
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.23.0.0/24
